version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: goia-shop-mysql
    environment:
      MYSQL_DATABASE: BancoGOIA
      MYSQL_USER: goia
      MYSQL_PASSWORD: goia123
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3306:3306"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
